services:
  web:
    build: .
    container_name: django_web
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - .:/app
      - static_volume:/app/static_collected  # Путь, куда собираются статические файлы
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: django_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      SECRET_KEY: ${SECRET_KEY:-django-insecure-default-key-change-me}
      DEBUG: 1
      ALLOWED_HOSTS: localhost,127.0.0.1,web,0.0.0.0
      DJANGO_SETTINGS_MODULE: cafeteria.settings
      STATIC_ROOT: /app/static_collected  # Правильно!
      STATIC_URL: /static/
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django_network

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static_collected:ro  # Исправлено: тот же путь, что и в web
    depends_on:
      - web
    networks:
      - django_network

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local

networks:
  django_network:
    driver: bridge